type = "card"
title = "Services"
description = "Professional services and community involvement."

[[items]]
title = "External Reviewer"
subtitle = "USENIX Security Symposium (USENIX Security)"
date = "2025"

[[items]]
title = "External Reviewer"
subtitle = "ACM Conference on Computer and Communications Security (CCS) "
date = "2025"
