type = "card"
title = "Teaching"
description = "Courses I have taught or assisted with."



[[items]]
title = "CISC260-010: Machine Organization and Assembly Language"
subtitle = "Teaching Assistant"
date = "Fall 2025 & Spring 2026"

[[items]]
title = "CISC469-010: Computer Security Principles and Practice"
subtitle = "Teaching Assistant"
date = "Fall 2025"

